### PR TITLE
odyssey-x86.coffee: Change flasher image to live image

### PR DESCRIPTION
**Pull request by lakshanthad**
Changelog-entry: Change odyssey-x86 flasher image to live image
Signed-off-by: Lakshantha Dissanayake <lakshanthad@seeed.cc>

### CODE REVIEW

**Comment by floion** [comment]
@resin-jenkins add to whitelist

**Review by floion — APPROVED** [review]

**Comment by lakshanthad** [comment]
@floion Thank you for the PR.

Can I know after how long the new image with the changes will appear on https://dashboard.balena-staging.com ?

**Comment by YossefAboukrat** [comment]
Hello, I have a problem. I have several Odysseys and most of them are solder emmc. I can't flash the emmc directly, is there a solution to bypass this pr and use the classic operation to flash a usb key and install it in the emmc on the Odyssey?

**Comment by lakshanthad** [comment]
Hello,
Could you please help to compile from source, use the "flasher image" and test it?

https://wiki.seeedstudio.com/BalenaOS-X86-Getting-Started/#q3-how-can-i-compile-balenaos-from-source-code

Please let me know your findings.

**Pull request merged**
